//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StatsEntities : DbContext
    {
        public StatsEntities()
            : base("name=StatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<covers_details> covers_details { get; set; }
        public virtual DbSet<covers_matchup> covers_matchup { get; set; }
        public virtual DbSet<mlb_game> mlb_game { get; set; }
        public virtual DbSet<mlb_game_history> mlb_game_history { get; set; }
        public virtual DbSet<mlb_pitcher> mlb_pitcher { get; set; }
        public virtual DbSet<mlb_serie> mlb_serie { get; set; }
        public virtual DbSet<mlb_team> mlb_team { get; set; }
        public virtual DbSet<mlb_team_history> mlb_team_history { get; set; }
        public virtual DbSet<covers_last> covers_last { get; set; }
        public virtual DbSet<covers_pitcher> covers_pitcher { get; set; }
        public virtual DbSet<covers_recent> covers_recent { get; set; }
        public virtual DbSet<mlb_teams_history> mlb_teams_history { get; set; }
        public virtual DbSet<mlb_view_games_by_update_date> mlb_view_games_by_update_date { get; set; }
        public virtual DbSet<view_schedule_mlb> view_schedule_mlb { get; set; }
    
        public virtual int setAllGamesNotUpdated()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("setAllGamesNotUpdated");
        }
    
        public virtual int sp_setAllGamesNotUpdated(Nullable<System.DateTime> game_date_start, Nullable<System.DateTime> game_date_end)
        {
            var game_date_startParameter = game_date_start.HasValue ?
                new ObjectParameter("game_date_start", game_date_start) :
                new ObjectParameter("game_date_start", typeof(System.DateTime));
    
            var game_date_endParameter = game_date_end.HasValue ?
                new ObjectParameter("game_date_end", game_date_end) :
                new ObjectParameter("game_date_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_setAllGamesNotUpdated", game_date_startParameter, game_date_endParameter);
        }
    
        public virtual int sp_setGamesNotLastVersion(Nullable<System.DateTime> game_date_start, Nullable<System.DateTime> game_date_end)
        {
            var game_date_startParameter = game_date_start.HasValue ?
                new ObjectParameter("game_date_start", game_date_start) :
                new ObjectParameter("game_date_start", typeof(System.DateTime));
    
            var game_date_endParameter = game_date_end.HasValue ?
                new ObjectParameter("game_date_end", game_date_end) :
                new ObjectParameter("game_date_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_setGamesNotLastVersion", game_date_startParameter, game_date_endParameter);
        }
    }
}
