//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonBestEntities : DbContext
    {
        public DonBestEntities()
            : base("name=DonBestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mlb_game> mlb_game { get; set; }
        public virtual DbSet<mlb_pitcher> mlb_pitcher { get; set; }
        public virtual DbSet<mlb_team> mlb_team { get; set; }
    }
}
