//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class covers_matchup
    {
        public int id { get; set; }
        public int eventid { get; set; }
        public string conference { get; set; }
        public string matchup { get; set; }
        public System.DateTime gamedate { get; set; }
        public string away { get; set; }
        public string home { get; set; }
        public string awaypitcher { get; set; }
        public string homepitcher { get; set; }
        public string url { get; set; }
        public System.DateTime createddatetime { get; set; }
    }
}
