//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class covers_details
    {
        public int eventid { get; set; }
        public int away_win { get; set; }
        public int away_lose { get; set; }
        public int home_win { get; set; }
        public int home_lose { get; set; }
    }
}
