//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class covers_pitcher
    {
        public int eventid { get; set; }
        public string away_pitcher { get; set; }
        public float away_era { get; set; }
        public string home_pitcher { get; set; }
        public float home_era { get; set; }
    }
}
