//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class covers_recent
    {
        public int eventid { get; set; }
        public System.DateTime date { get; set; }
        public string away_team { get; set; }
        public string home_team { get; set; }
        public int away_score { get; set; }
        public int home_score { get; set; }
        public string away_pitcher { get; set; }
        public float away_ip { get; set; }
        public string home_pitcher { get; set; }
        public float home_ip { get; set; }
    }
}
