//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class covers_last
    {
        public int eventid { get; set; }
        public string team { get; set; }
        public System.DateTime datetime { get; set; }
        public string vrs { get; set; }
        public string result { get; set; }
        public string score { get; set; }
        public string starter_pitcher { get; set; }
        public float starter_ip { get; set; }
        public string oppenent_pitcher { get; set; }
        public float opponent_ip { get; set; }
    }
}
