//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mlb_team
    {
        public int id_team { get; set; }
        public string team_name { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string L10 { get; set; }
        public Nullable<int> actualPosition { get; set; }
        public string league { get; set; }
        public string division { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
        public Nullable<int> win { get; set; }
        public Nullable<int> lost { get; set; }
    }
}
