//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mlb_game
    {
        public Nullable<System.DateTime> game_date { get; set; }
        public int game_id { get; set; }
        public int game_serie_id { get; set; }
        public Nullable<int> game_number { get; set; }
    }
}
