//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mlb_serie
    {
        public int serie_id { get; set; }
        public int mlb_game_id { get; set; }
        public Nullable<int> mlb_quantity_games { get; set; }
    }
}
