//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mlb_pitcher
    {
        public int pitcher_id { get; set; }
        public string pitcher_name { get; set; }
        public Nullable<double> pitcher_era { get; set; }
        public Nullable<double> pitcher_last3_era { get; set; }
    }
}
